### PR TITLE
Josh branch1

### PR DESCRIPTION
**Pull request by Josh-Webb**
Issue number 2.  Finished as much as can be for now.  Can purchase and assign grazing animals to grazing field.  Will need to implement other animal facilities to implement fully.

### CODE REVIEW

**Review by keishacard — APPROVED** [review]
🐮

**Review by jimmymetts — COMMENTED** [review]
🥓

**Comment by hcleland** [comment]
Works like a farm! 👍

**Review by hcleland — APPROVED** [review]
Works like a farm! 👍

**Pull request merged**
